#!/bin/bash

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

DB_URL="sqlite3://db/db.sqlite3"

if [ $# -eq 0 ]; then
    set -- "up"
fi

migrate -database "${DB_URL}" -path "${ROOT}/migrations" "$@"
